// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk2Pxtd_0plwA8eGyXXlABJywQFk3SokQ',
    appId: '1:778466348549:android:92ad6cad1c5bde2c81566c',
    messagingSenderId: '778466348549',
    projectId: 'ai-fitness-coach-project',
    storageBucket: 'ai-fitness-coach-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQjwvix8MWPDv7Fk_P3Vt6iIES4Dh2BNE',
    appId: '1:778466348549:ios:fdfd83beee218c6281566c',
    messagingSenderId: '778466348549',
    projectId: 'ai-fitness-coach-project',
    storageBucket: 'ai-fitness-coach-project.firebasestorage.app',
    iosBundleId: 'com.example.aiFitnessCoach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGpsJ4HSIP6nmZR3P-89YR9HyMSk9dw6w',
    appId: '1:778466348549:web:7340896f5fd9549381566c',
    messagingSenderId: '778466348549',
    projectId: 'ai-fitness-coach-project',
    authDomain: 'ai-fitness-coach-project.firebaseapp.com',
    storageBucket: 'ai-fitness-coach-project.firebasestorage.app',
  );
}